### ISSUE TITLE
Flatpak: Can't access USB drive for journal storage

### ISSUE THREAD

**Issue by mcain99** [LukeBriggsDev/Pepys#13]
I'm using the flatpak version of Pepys and I moved my journal to a USB drive.  I updated the config file to point to the new location of my journal, however Pepys couldn't access it.  I noticed the flatpak permissions only include the `home` directories.  
On my system I manually added filesystem permission for Pepys to the `/media` directory and this solved my problem (`sudo flatpak override dev.lukebriggs.pepys --filesystem=/media/`). 
I submitted this in hopes of getting this added to the flatpak version, but I do not know if there are any downsides to adding this directory to the permissions.  I'm also using Linux Mint and I'm not familiar with other distros to know if they auto mount drives to the `/media` directory or to another.

**Comment by LukeBriggsDev** [comment]
Thanks for raising this issue!

/media is now accessible from within the flatpak
