### ISSUE TITLE
Fails to launch on Windows

### ISSUE THREAD

**Issue by conor-byrne** [LukeBriggsDev/Pepys#2]
Version: 1.0.3 and 1.0.2
OS: Windows 10

Crashes immediately on start.

**Comment by LukeBriggsDev** [comment]
There are peculiar crashing issues on WIndows. The problem lies in the actual C++ running of the Qt Framework and so it doesn't throw very useful exceptions. I will continue to investigate.

In the mean time, as a temporary fix, try restarting your pc and opening the application up again.

**Comment by LukeBriggsDev** [comment]
Actually, I have located the particular issue you are encountering.

I made the rookie mistake of not shipping a thick venv. A fix should be out within the next 24 hours.

**Comment by LukeBriggsDev** [comment]
I believe I have fixed this issue. Please try the new installer available [here](https://github.com/LukeBriggsDev/Pepys/releases/tag/v1.0.4). Thank you so much for bringing it to my attention. 

I would greatly appreciate it if you could reply with whether the issue is resolved on your end.

**Comment by conor-byrne** [comment]
All fixed! Thanks!
