### ISSUE TITLE
[BUG] - Uninstall does not remove ARP Entry

### ISSUE THREAD

**Issue by Trenly** [LukeBriggsDev/Pepys#23]
**Describe the bug**
When uninstalling Pepys, the entry still remains in appwiz.cpl

**To Reproduce**
1. run `winget install pepys -s winget`
2. Wait for the install to finish
3. Open appwiz.cpl
4. Double click on Pepys and confirm the uninstall
5. Wait for the uninstall to finish
6. Refresh appwiz.cpl
7. Note the app still appears

**Expected behavior**
Uninstall removes the Registry Entries for Pepys

**Screenshots**
``- None -``

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 build 19041.1586
 - Version: Pepys 1.5.0

**Additional context**
This bug causes winget to think the application is installed when it isn't

**Comment by LukeBriggsDev** [comment]
@Trenly Thanks for pointing this out. This has been fixed for the installer on the v1.5.3 releases page and v1.5.3 is now available through winget.
