### ISSUE TITLE
Windows installer window title

### ISSUE THREAD

**Issue by conor-byrne** [LukeBriggsDev/Pepys#3]
Installer name seems to be a "your name here" default.

![image](https://user-images.githubusercontent.com/15220966/120508130-607e6c80-c3bf-11eb-85dd-07f6b6e87e13.png)

**Comment by LukeBriggsDev** [comment]
This has been fixed in the [latest release](https://github.com/LukeBriggsDev/Pepys/releases/tag/v1.0.5) within commit 970275b13c17d8b7313e8150dac6fa4a42a26793
