### ISSUE TITLE
Unable to run Pepys Flatpak on Ubuntu

### ISSUE THREAD

**Issue by manikandancode** [LukeBriggsDev/Pepys#4]
OS: Ubuntu 21.04 ( 64-bit)

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/app/bin/runner.sh: line 1:     3 Aborted                 (core dumped) python3 /app/src/main/python/main.py

**Comment by LukeBriggsDev** [comment]
Hi! Thank you for raising this issue. I have just pushed an update to flathub that should resolve this issue. Please download the latest update for flathub and let me know if the issue is resolved on your end.

**Comment by manikandancode** [comment]
Thanks. Working.
