### ISSUE TITLE
Suggestions regarding spell checker and fonts

### ISSUE THREAD

**Issue by r-palmeira-pt** [LukeBriggsDev/Pepys#7]
I suggest there should be options for changing the spell checker dictionary or just disable it. 
It would help if there was a menu to control the text font and size.  
If it would be possible to retain these settings between sessions, it would be ideal.

**Comment by LukeBriggsDev** [comment]
Hi @r-palmeira-pt thanks for the suggestion. I have just put out a new release (v1.1.1) that includes a text size adjuster and the ability to disable the spell checker (both of these are saved between sessions)

I have not included the ability to change the font as I need to ensure the fonts are monospace to allow for certain markdown blocks (such as tables) to remain readable.
